version: 2

orbs:
  android: circleci/android@3.1.0
  auto_ci: nowsecure/ci-auto-orb@1.2.1
  
jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew assembleDebug --stacktrace --no-daemon
      - auto_ci/mobile_security_test:
          auto_file: /tmp/myworkspace/test.apk
          auto_wait: "30"
          auto_score: "50"
          auto_show_status_messages: "true"

