version: 2.1

orbs:
  android: circleci/android@3.1.0
  auto_ci: nowsecure/ci-auto-orb@1.2.1
  
jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1
      
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew assembleDebug --stacktrace --no-daemon
      - persist_to_workspace: # Persist the specified paths (workspace/echo-output)
      # into the workspace for use in downstream job. Must be an absolute path,
      # or relative path from working_directory. This is a directory on the container which is
      # taken to be the root directory of the workspace.
          root: .
            # Must be relative path from root
          paths:
            - ./app/k9mail/build/outputs/apk/debug/


  scan:
    docker:
       - image: openjdk:8
       
    steps:
       - attach_workspace:
           at: .
          
       - auto_ci/mobile_security_test:
           auto_file: k9mail-debug.apk
           auto_wait: "90"
           auto_score: "50"
           auto_show_status_messages: "true"

workflows:
  build_and_scan:
    jobs:
      - build
      - scan:
          requires:
           - build


