version: 2.1

orbs:
  android: circleci/android@3.1.0
  auto_ci: nowsecure/ci-auto-orb@1.2.1
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1

    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew assembleDebug --stacktrace --no-daemon
      - auto_ci/mobile_security_test:
          auto_file: ./app/k9mail/build/outputs/apk/debug/k9mail-debug.apk
          auto_wait: "90"
          auto_score: "50"
          auto_show_status_messages: "true"

  lint:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint