version: 2

orbs:
  android: circleci/android@3.1.0
  
jobs:
  build:
    docker:
      - image: cimg/android:2021.08.1
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew assembleDebug --stacktrace --no-daemon
      - store_artifacts:
            path: build/libs
