version: 2

orbs:
  android: circleci/android@3.1.0
  
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: openjdk:11
        environment:
            # Customize the JVM maximum heap limit
            JVM_OPTS: -Xmx500m
            TERM: dumb
        steps:
            - checkout
            - run: ./gradlew dependencies
            - run: ./gradlew assembleDebug --stacktrace --no-daemon
            - store_artifacts:
                  path: build/libs
