name: "NowSecure GHAS Test"

on:
 
  workflow_dispatch:
    branches: [ main ]

jobs:
    
  process:
    runs-on: ubuntu-latest
    # The above stage we introduced.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v3
        timeout-minutes: 30
        with:
          report_id: 8c7fdf66-b63f-11ed-ac54-d765fca77473
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace the Group ID.
          group_id: "602abed9-4c66-453d-8431-da0195b682de"
          
          
      - name: echo output
        run: |
         echo ${{process.outputs.*}}
   

    
